version: 0.2

phases:
  pre_build:
    commands:
      - echo pre build block
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=730186024834.dkr.ecr.us-east-1.amazonaws.com/codebuildapp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  
  build:
    commands:
      - docker --version
      - service docker start
      - echo build block
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo post build block
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"nodeApp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefiniton.json
      
artifacts:
     files: imagedefiniton.json
  
